### ISSUE TITLE
It's possible to scan QR codes on iOS

### ISSUE THREAD

**Issue by axhamre** [expo/snack-web#10]
You're probably fully aware about this already, but scanning QR codes with the camera on an iOS device works perfectly. Despite the [message](https://github.com/expo/snack-web/blob/71746fa2761b1b989ae43b61717c2e254d6e0698/src/client/components/DeviceInstructions/WhyNoQrBanner.tsx):

`* As of March 29, 2018 , the Expo client on iOS can no longer scan QR codes. Read more.`

I don't know if there has always been a semantic glitch, i.e. that the camera always has worked on iOS but not the Expo client. However, it's a pity to mislead as it works fine if you just scan with the camera app.

I'm on an iPhone SE and iOS 12.1.

**Comment by satya164** [comment]
AFAIK it has something to do with Apple's guidelines.

cc @brentvatne

**Comment by yehee** [comment]
Hi! I would like to follow up on this thread. I noticed that I cannot open the Expo project under someone else's Expo account on my iPhone which I logged in using my credentials. Is it possibly being fixed? It would be really handy if I could share my app with other people through QR code scan.

**Comment by brentvatne** [comment]
this is available to teammates with a developer services account: https://expo.io/developer-services

**Comment by yehee** [comment]
Thanks! Would appreciate if it's more clearly stated along with the message 👍

**Comment by IjzerenHein** [comment]
Hi! We've already removed this message a while ago. Closing this :)
