### ISSUE TITLE
Can't install package from the github.

### ISSUE THREAD

**Issue by astriskit** [expo/snack-web#11]
Following this guide, https://docs.npmjs.com/files/package.json#git-urls-as-dependencies, currently, it is not possible to import the github repos. I'm not sure if it is a feature incompleteness or bug or 'wont-be-a-feature'.

**Comment by IjzerenHein** [comment]
We do support github imports. This issue does not clearly describe what the problem is. Feel free to reopen with a clear issue description if this is still an issue for you.
