### ISSUE TITLE
Import GitRepository

### ISSUE THREAD

**Issue by LucaPaterlini** [expo/snack-web#12]
Hello,
I am trying the course CS50M to improve my knowledge about react native.
They strongly suggest your ide so I would like to know which path
do I have to enter 

when your UI asks me to

"Import an Expo project from a Git repository.
Git URL"

I have tried with this URL but I always get the red error message.
"
An error occurred during import. This could be because the data provided was invalid, or because the repository referenced is not a properly formatted Expo project.
"

Thank you in advance for your reply, 
Best Regards,
LP

**Comment by satya164** [comment]
Hey! Can you share the URL you used so I can try it?

**Comment by LucaPaterlini** [comment]
my bad, I thought I have added it https://github.com/LucaPaterlini/CS50MProject1/tree/master/app

**Comment by satya164** [comment]
thank you. I'll take a look soon.

**Comment by nitaking** [comment]
👍

**Comment by joebochill** [comment]
@LucaPaterlini your link is referring to an /app folder in your master branch, which does not exist. Your link would be: https://github.com/LucaPaterlini/CS50MProject1 but this project does not look like it was created using the Expo CLI.

**Comment by tcdavis** [comment]
@LucaPaterlini You also need the project to be specified for a currently supported version of the expo SDK.  Updating to SDK 36 imports as expected https://github.com/tcdavis/CS50MProject1
