### ISSUE TITLE
Is it possible to change sdkVersion for a snack?

### ISSUE THREAD

**Issue by adititipnis** [expo/snack-web#14]
My problem is that a part of my code does not work in my snack. But the same code works when copied in another snack. When I downloaded the code for both these projects it seems the only difference is the **sdkVersion** which is specified in **app.json** file. (My snack is using  `"sdkVersion": "32.0.0"` while the snack where the code works is using `"sdkVersion": "26.0.0"`. 

The app.json file is not visible when I browse to the snack link. It seems it can only be accessed when I export the file. Now I know I could run the app locally with the changed version but I would like to continue working in the snack online environment. Is there a solution to this?

Thanks :)

**Comment by satya164** [comment]
You can change the version on the bottom right corner.
