### ISSUE TITLE
!ASAP! SDK v32 is down on snack.expo.io

### ISSUE THREAD

**Issue by oxyii** [expo/snack-web#16]
Subj. On v31 snack works well for now

![Выделение_001](https://user-images.githubusercontent.com/39907210/54634076-74fe1500-4a92-11e9-9470-7a68b5782a45.png)

**Comment by satya164** [comment]
Thanks. Looking now.

**Comment by tcdavis** [comment]
Thank you so much for bringing to our attention.  Should be resolved now.

**Comment by oxyii** [comment]
@tcdavis Yep. Looking works now. Thank you for great project and for quick resolve
