### ISSUE TITLE
Import GitRepository 

### ISSUE THREAD

**Issue by yehoan** [expo/snack-web#17]
i  not  know  why   i  not  can import  a Git repository  
it is show  us  this  An error occurred during import. This could be because the data provided was invalid, or because the repository referenced is not a properly formatted Expo project.
but  actually   it  is  really  use  expo  so  tell me  the  reason   okay  thanks

**Comment by zzzgit** [comment]
https://github.com/zzzgit/chat
I can't import mine also.
What's the problem?

**Comment by joebochill** [comment]
@zzzgit your project imports fine for me (https://snack.expo.io/@git/github.com/zzzgit/chat) but it looks like you are running into the same problems with dependencies as I've been battling with (#25)

**Comment by tcdavis** [comment]
Most issues with project imports are caused by one of three issues:
- the repo is not a valid Expo project
- the repo is a valid expo project but uses a version of the Expo SDK that is no longer supported
- the repo includes a dependency in package.json that cannot be successfully bundled
