### ISSUE TITLE
Snack-web crashed on Centos 7.0

### ISSUE THREAD

**Issue by sanyaade-teachings** [expo/snack-web#22]
Hello Everybody,

First thanks for the very good job, efforts and your valuable time put into this toolkit.

I followed steps outline in the readme but clone the repo, issued commands, etc...
Then I issue the yarn start command, the server start but the hotel app crashed. Please see below the screenshot of it:

![image](https://user-images.githubusercontent.com/4993211/57976378-4a6b0280-79d6-11e9-942d-0c13f1b0186a.png)

I think it is the following: ==> /var/www/html/site6/snack-web/node_modules/nullthrows/nullthrows.js:9
  throw error;
  ^

Please help!
Hear from you soon!
Many thanks for your continuous support.

God blesses!!!

Best regards,
Sanyaade

**Comment by tcdavis** [comment]
Hi @sanyaade-teachings, I think you are missing the environment variables here: https://github.com/expo/snack-web#pre-requisites

**Comment by sanyaade-teachings** [comment]
@tcdavis ,

Many thanks for your reply. I will have a look and give it another try!

God blesses!!!

Best regards,
Sanyaade
