### ISSUE TITLE
Code completion and line number feature are not working on iPad

### ISSUE THREAD

**Issue by pandaxbacon** [expo/snack-web#24]
I tried it on both Safari and Chorme. Both can not show the completion suggestions. Is there any config I can tweak to get it work? Thanks

**Comment by pandaxbacon** [comment]
The autocompletion feature is back if you request a desktop version, but once you did that. It will not recognise the arrow keys key-press.

**Comment by satya164** [comment]
We use Monaco editor which maybe doesn't have proper support for iPad yet

**Comment by pandaxbacon** [comment]
Got it thanks @satya164
