### ISSUE TITLE
firebase error

### ISSUE THREAD

**Issue by thareekanvar** [expo/snack-web#26]
But this Working locally ... only i get error  in snack expo ..so i think its error of snack .. any one can tell me .. what happends..?? 

{
  "dependencies": {
    "uuid": "3.3.2",
    "firebase": "5.2.0",
    "react-navigation": "2.6.0",
    "react-navigation-header-buttons": "^1.2.1",
    "firebase/firestore": "7.0.0"
  }
}
firebase.firestore is not a function. (In 'firebase.firestore()', 'firebase.firestore' is undefined)
  Evaluating module://Fire.js.js
  Evaluating module://screens/FeedScreen.js.js
  Evaluating module://App.js.js
  Loading module://App.js

https://snack.expo.io/@sadikali.mm/github.com-evanbacon-firebase-instagram@@evanbacon-tutorial?session_id=snack-session-6!ZPkupfR

**Comment by tcdavis** [comment]
Hi @thareekanvar, this is a symptom of some differences between the way snack and your local development environment handle dependencies. https://github.com/expo/snack-sdk#differences-between-dependencies-in-snack-and-npm

Unfortunately I'm not aware of a workaround that would allow the side effects in firebase/firestore to modify the firebase object from firebase.
