### ISSUE TITLE
Embedding does not work

### ISSUE THREAD

**Issue by andermoran** [expo/snack-web#27]
When using the code generated to embed an expo snack in HTML, it only produces a blank canvas. Have tested multiple different projects and browsers. Other people seem to have this problem to. To replicate, go to snack.expo.io, save, then generate the embedded code and try to put that into a website.

**Comment by tcdavis** [comment]
Hi @andermoran, we test the embeds here https://github.com/expo/snack-web/blob/master/snack-embed.html and they are being used in a lot of places like https://facebook.github.io/react-native/docs/handling-touches so I suspect your issue has been resolved.  Could you reopen if you are still experiencing it?
