### ISSUE TITLE
Using TypeORM in Snack makes Snack run out of memory in Chrome

### ISSUE THREAD

**Issue by erik-smit** [expo/snack-web#28]
Example: https://snack.expo.io/@smitel/typeorm-snack-oom

I took the sample snack, added typeorm/browser to the imports and package.json and now Chrome runs out of memory with an 'Aw, Snap!' when trying to load it. Watching it in task manager shows it to peak at 6GB.

It doesn't seem to happen when the blue warning of slow network appears.

Also doesn't seem to happen with Firefox.

Any clue?

**Comment by erik-smit** [comment]
When viewing the Memory tab in the Developer Tools I do not see the growth in Memory usage that I do see in the task manager.

![image](https://user-images.githubusercontent.com/1376121/66027292-dfd8e000-e4fa-11e9-8c71-bd859214cfac.png)

Any hints in how to debug where this memory goes?

**Comment by satya164** [comment]
> It doesn't seem to happen when the blue warning of slow network appears.

The difference is that we're using Monaco if network isn't slow. Maybe a bug with Monaco and the TS language server that it uses 🤔

**Comment by IjzerenHein** [comment]
Hi! I was unable to reproduce this problem. Here is the Snack I used:
https://snack.expo.io/9b06p-w87

It's very likely that this has already been fixed along the way.

Please report any new issues in the new https://github.com/expo/snack monorepo, as this repository will be archived.
