### ISSUE TITLE
Import Git Respository

### ISSUE THREAD

**Issue by ariel-narciso** [expo/snack-web#29]
I am trying to import git repository, but i get the following error: "An error occurred during import. This could be because the data provided was invalid, or because the repository referenced is not a properly formatted Expo project."

Git repository: https://github.com/ariel-narciso/eco-exploracao

The project was created with the following command: expo init 'nameProject'

**Comment by tcdavis** [comment]
Most issues with project imports are caused by one of three issues:

the repo is not a valid Expo project
the repo is a valid expo project but uses a version of the Expo SDK that is no longer supported
the repo includes a dependency in package.json that cannot be successfully bundled
