### ISSUE TITLE
Can I lock orientation like through app.json?

### ISSUE THREAD

**Issue by moshfeu** [expo/snack-web#37]
I would like to lock `orientation` option like I do with local project

```
"orientation": "portrait" 
```

https://docs.expo.io/versions/latest/workflow/configuration/#orientation

**Comment by IjzerenHein** [comment]
Hi! :wave: 

A bit late, but here is a way to do lock the screen orientation. 
`app.json` is not supported in Snack, however you can use the [Screen Orientation API](https://docs.expo.io/versions/latest/sdk/screen-orientation/).

This Snack demonstrates how to lock your app in Landscape mode:
https://snack.expo.io/ED!9T_xtA
