### ISSUE TITLE
Unable to import reanimated

### ISSUE THREAD

**Issue by computerjazz** [expo/snack-web#41]
When `import Animated from "react-native-reanimated"` using `expo 36` or `expo 35` I'm getting the following error:
```js
Device: (0:0) Unable to resolve module 'module://fbjs/lib/invariant.js'
  Evaluating module://fbjs/lib/invariant.js
  Evaluating module://react-native-reanimated.js
  Evaluating module://App.js.js
  Loading module://App.js
```

`expo 34` works.

Repro:
https://snack.expo.io/@computerjazz/reanimated-bug

Thanks!

**Comment by jtomaszewski** [comment]
Strangely, the example you linked in here ( https://snack.expo.io/@computerjazz/reanimated-bug ) works for me, on both Expo 36 and 37.

However, I have the exact same error on [a snack example of `createMaterialTopTabNavigator`](https://snack.expo.io/?platform=android&name=createMaterialTopTabNavigator%20%7C%20React%20Navigation&dependencies=%40react-native-community%2Fmasked-view%400.1.7%2C%40react-navigation%2Fbottom-tabs%405.2.4%2C%40react-navigation%2Fdrawer%405.3.4%2C%40react-navigation%2Fmaterial-bottom-tabs%405.1.6%2C%40react-navigation%2Fmaterial-top-tabs%405.1.6%2C%40react-navigation%2Fnative%405.1.3%2C%40react-navigation%2Fstack%405.2.6%2Creact-native-reanimated%401.7.0%2Creact-native-safe-area-context%400.7.3%2Creact-native-screens%402.4.0&sourceUrl=https%3A%2F%2Freactnavigation.org%2Fexamples%2F5.x%2Fmaterial-top-tab-based-navigation-minimal.js) that is linked on https://reactnavigation.org/docs/material-top-tab-navigator/ (Expo 37) .

![image](https://user-images.githubusercontent.com/1862580/81534064-a48f7100-9367-11ea-9908-973e9498f641.png)

The bug appears for me on both web preview and iOS preview (after I scan the QR code on my actual iPhone ).

Have you found any workaround for it?

I've read somewhere that adding `fbjs` as a dependency to package.json should resolve the problem ( https://github.com/expo/expo/issues/6510#issuecomment-565622923 ), but on snack-web it doesn't.

**Comment by jtomaszewski** [comment]
However, the example you linked in here ( https://snack.expo.io/@computerjazz/reanimated-bug ) works for me, on both Expo 36 and 37.

**Comment by jtomaszewski** [comment]
FYI, the bug appears for me on both web preview and iOS preview (after I scan the QR code on my actual iPhone ).

**Comment by jtomaszewski** [comment]
I got it resolved somehow. After bumping all my package.json deps to recent versions, the problem disappeared. (And there's no need for `fbjs` to be imported then.)

**Comment by satya164** [comment]
Yea, make sure you bump the versions in package.json and it'll work.
