### ISSUE TITLE
No examples from React navigation docs working on Snack - Attempted to assign to readonly property

### ISSUE THREAD

**Issue by faisalchishtii** [expo/snack-web#44]
None of the React navigation examples working on the web for me:

**All examples are giving below error:** 
https://reactnavigation.org/docs/drawer-based-navigation/

> Device: (900:881) Attempted to assign to readonly property.
>   Evaluating module://@react-navigation/native.js
>   Evaluating module://@react-navigation/drawer.js
>   Evaluating module://App.js.js
>   Loading module://App.js

![image](https://user-images.githubusercontent.com/26409919/80183611-c3cb9600-8626-11ea-9741-e9921b9ce90b.png)

I am getting same error when I try it using the Expo appon my Android device.

**Comment by joshglenn** [comment]
I am also having this same problem

**Comment by joshglenn** [comment]
I looked into this a little further. 

Maintainers: could it have something to do with [this](https://github.com/webpack/webpack/issues/4039#issuecomment-419284940)?

And is it an expo snack-web issue or a react-navigation issue?

**Comment by joshglenn** [comment]
To get a little more insight into this:

In the [Hello React Navigation page](https://reactnavigation.org/docs/hello-react-navigation) of react-navigation's docs, the first snack example link is [this](https://snack.expo.io/?platform=android&name=App%20containers%20%7C%20React%20Navigation&dependencies=%40react-native-community%2Fmasked-view%40%5E0.1.7%2C%40react-navigation%2Fnative%40%5E5.1.3%2C%40react-navigation%2Fbottom-tabs%40%5E5.2.4%2C%40react-navigation%2Fdrawer%40%5E5.3.4%2C%40react-navigation%2Fmaterial-bottom-tabs%40%5E5.1.6%2C%40react-navigation%2Fmaterial-top-tabs%40%5E5.1.6%2C%40react-navigation%2Fstack%40%5E5.2.6%2Creact-native-reanimated%40%5E1.7.0%2Creact-native-safe-area-context%40%5E0.7.3%2Creact-native-screens%40%5E2.4.0&sourceUrl=https%3A%2F%2Freactnavigation.org%2Fexamples%2F5.x%2Fhello-react-navigation.js)

And as of this writing, it does not work. But if you edit the package.json inside the snack, and change it from this:

```
{
  "dependencies": {
    "@react-native-community/masked-view": "^0.1.7",
    "@react-navigation/native": "^5.1.3",
    "@react-navigation/bottom-tabs": "^5.2.4",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.4.0",
    "@react-navigation/drawer": "^5.3.4",
    "react-native-reanimated": "^1.7.0",
    "@react-navigation/material-bottom-tabs": "^5.1.6",
    "react-native-paper": "^3.0.0",
    "@react-navigation/material-top-tabs": "^5.1.6",
    "react-native-tab-view": "^2.0.0",
    "@react-navigation/stack": "^5.2.6"
  }
}
```

to this:

```
{
  "dependencies": {
    "@react-native-community/masked-view": "0.1.7",
    "@react-navigation/native": "5.1.3",
    "@react-navigation/bottom-tabs": "^5.2.4",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "2.4.0",
    "@react-navigation/drawer": "^5.3.4",
    "react-native-reanimated": "^1.7.0",
    "@react-navigation/material-bottom-tabs": "^5.1.6",
    "react-native-paper": "^3.0.0",
    "@react-navigation/material-top-tabs": "5.1.6",
    "react-native-tab-view": "^2.0.0",
    "@react-navigation/stack": "5.2.6"
  }
}
```

It will begin to work.

**Comment by joshglenn** [comment]
What do you think is the solution to this?

When I started learning Expo, one of my key pain points was this: When I try a snack, 80% of the time they were broken. That was a real pain. I know it has to do with the nature of npm's package system. So many projects don't lock their versions down, so one repo updates and breaks apps and snacks all over the ecosystem. 

I was taking a look at that snack link that I posted in my last comment... and I see that the dependencies are coded in there. Is it safe to say that they (in this case React navigation) should lock down the version numbers in their example snacks and/or projects if they want to keep this from happening?

**Comment by joshglenn** [comment]
@faisalchishtii to make the first snack work on that page you mentioned, open the snack, and change package.json to:

```
{
  "dependencies": {
    "@react-native-community/masked-view": "0.1.7",
    "@react-navigation/native": "5.1.3",
    "@react-navigation/bottom-tabs": "5.2.4",
    "react-native-safe-area-context": "0.7.3",
    "react-native-screens": "2.4.0",
    "@react-navigation/drawer": "5.3.4",
    "react-native-reanimated": "1.7.0",
    "@react-navigation/material-bottom-tabs": "5.1.6",
    "react-native-paper": "3.0.0",
    "@react-navigation/material-top-tabs": "5.1.6",
    "react-native-tab-view": "2.8.0",
    "@react-navigation/stack": "5.2.6"
  }
}
```

That got it working for me.



> None of the React navigation examples working on the web for me:
> 
> **All examples are giving below error:**
> https://reactnavigation.org/docs/drawer-based-navigation/
> 
> > Device: (900:881) Attempted to assign to readonly property.
> > Evaluating module://@react-navigation/native.js
> > Evaluating module://@react-navigation/drawer.js
> > Evaluating module://App.js.js
> > Loading module://App.js
> 
> ![image](https://user-images.githubusercontent.com/26409919/80183611-c3cb9600-8626-11ea-9741-e9921b9ce90b.png)
> 
> I am getting same error when I try it using the Expo appon my Android device.

**Comment by IjzerenHein** [comment]
Hi 👋 

The issues with Snack and react-navigation have been resolved.
I'm going to close this but feel free with new reproduction steps if this still happens for you. 👍
