### ISSUE TITLE
web-player static script fetch failed (local cloned)

### ISSUE THREAD

**Issue by milearn** [expo/snack-web#49]
Hi,
After cloning this repo. I'm facing an issue where I'm getting `(failed)net::ERR_EMPTY_RESPONSE` for `app.34240727.chunk.js`.

This script is injected in `/web-player/index.html?initialUrl=...`  html file and script file is mandatory to preview. Attaching screenshot below:

<img width="1269" alt="Screenshot 2020-07-02 at 10 37 56 PM" src="https://user-images.githubusercontent.com/10200019/86390009-e0ceb600-bcb4-11ea-8d84-627d3c480dbb.png">

I'm using `SNACK_APP_URL = http://s3.us-west-1.amazonaws.com/snack-web-player/36`

Please fix this issue

**Comment by milearn** [comment]
@tcdavis Please check if you can help here.

**Comment by IjzerenHein** [comment]
Hi! I'm sorry this repository has not been maintained for some time. We have just moved the Snack web app to the new Snack monorepo at https://github.com/expo/snack

You can find instructions on how to run the Snack web-app here:
https://github.com/expo/snack/blob/main/CONTRIBUTING.md

The `expo/snack-web` repo will be archived, please report any new/existing issues in the new https://github.com/expo/snack repository.
