### ISSUE TITLE
Missing dev dependency?

### ISSUE THREAD

**Issue by msanatan** [expo/snack-web#5]
Hey,

So I set this up on my local machine and had to do two things differently from the instructions:

1. `yarn install --production=false` to get dev dependencies like gulp included
1. `yarn add isomorphic-fetch` as it's a missing dependency

Without isomorphic-fetch I get these errors:

```
ERROR in ./snack/auth/withAuth.js
Module not found: Error: Can't resolve 'isomorphic-fetch' in '/Users/marcussanatan/projects/snack-web/snack/auth'
 @ ./snack/auth/withAuth.js 13:0-26
 @ ./snack/components/App.js
 @ ./snack/components/Router.js
 @ ./snack/index.js
 @ multi ./snack/index

ERROR in ./snack/auth/authManager.js
Module not found: Error: Can't resolve 'isomorphic-fetch' in '/Users/marcussanatan/projects/snack-web/snack/auth'
 @ ./snack/auth/authManager.js 57:0-26
 @ ./snack/components/App.js
 @ ./snack/components/Router.js
 @ ./snack/index.js
 @ multi ./snack/index

ERROR in ./snack/components/DeviceInstructions/SendProjectLink.js
Module not found: Error: Can't resolve 'isomorphic-fetch' in '/Users/marcussanatan/projects/snack-web/snack/components/DeviceInstructions'
 @ ./snack/components/DeviceInstructions/SendProjectLink.js 13:0-26
 @ ./snack/components/DeviceInstructions/AccountTab.js
 @ ./snack/components/DeviceInstructions/DeviceInstructionsModal.js
 @ ./snack/components/Preferences/PreferencesProvider.js
 @ ./snack/index.js
 @ multi ./snack/index
```

The dev dependencies produce more if not installed. Not sure if they're missing from the instructions, I missed some of the instructions, if my setup doesn't meet requirements or something else.

By the way, isomorphic-fetch is not actively developed as well, maybe something like [cross-fetch](https://github.com/lquixada/cross-fetch) which is actively maintained can be used instead?

**Comment by tcdavis** [comment]
isomorphic-fetch is a transitive dependency brought in by react-router-dom, so it should be available to you without dev dependencies or manual install steps
