### ISSUE TITLE
Importing repository from GitHub uses incorrect SDK version

### ISSUE THREAD

**Issue by joebochill** [expo/snack-web#53]
When I import a project from GitHub that's using version 38 of the SDK, it loads up in snack using version 37.  I'm using some of the changes from 38, so this makes the application crash.

Is there a way to force Snack to load with a particular version of the SDK (e.g., via a query string parameter perhaps), or some configuration I can set in my repository?

My primary use case is being able to share the link with people for them to play with a demo. Seeing the red screen of death and then manually changing the SDK version and reloading is not the ideal workflow.

Edit:
Link to reproduction example (this is a fresh blank project built with Expo): https://snack.expo.io/@git/github.com/joebochill/testsnack38
Expo version specified in package.json: https://github.com/joebochill/testsnack38/blob/master/package.json#L11

**Comment by joebochill** [comment]
I did some digging in the source and found that you _can_ in fact specify the SDK version in the URL via `&sdkVersion=38.0.0`.

This loads it up with the correct version selected, but it doesn't seem like the device preview is actually using that version. It throws the same error that I was seeing when it loads with 37 (I'm using things from the updated version of react-native-safe-area-context in sdk 38):
`Device: requireNativeComponent: "RNCSafeAreaProvider" was not found in the UIManager.`

If I use the dropdown to toggle to 37, then back to 38 and save, then the project runs fine.

**Comment by IjzerenHein** [comment]
Hi! 👋 

You can indeed specify `sdkVersion=38.0.0` to load a specific version, or use `sdkVersion=latest` to load the most recent SDK version.

We've recently improved dependency management in Snack which makes transitioning between SDK versions are lot easier. You will see warnings/errors when versions are not compatible with the selected SDK and prompts to fix those. And where possible Snack now automatically updates the version when you select a different SDK.

Hope this helps 👍

**Comment by joebochill** [comment]
Looks like it's working as expected now @IjzerenHein, thanks!
