### ISSUE TITLE
Expo Snack won't work in any browser with clear cache (Cannot read property 'deviceConnectionMethod' of null)

### ISSUE THREAD

**Issue by behrends** [expo/snack-web#6]
This is a critical bug as Expo Snack won't load in any browser that hasn't visited snack.expo.io before. So almost everybody is affected, especially people trying Expo Snack for the first time.

(This issue has originally been posted to Expo's main repo: [github.com/expo/expo/issues/2646](https://github.com/expo/expo/issues/2646)

### Steps to Reproduce

1. Make sure you open a new private browser tab
2. Open https://snack.expo.io

### Expected Behavior

Snack Expo is successfully opened

### Actual Behavior

![image](https://user-images.githubusercontent.com/50868/48120399-4cf3df00-e272-11e8-9956-5e01d9dde7d1.png)

### Reproducible Demo

https://snack.expo.io in private browser tab

**Comment by behrends** [comment]
See also this pull request #7

**Comment by behrends** [comment]
Found this quick workaround:

 -   Open JavaScript-Console in browser and run this:
 -   window.localStorage.setItem('__SNACK_EDITOR_CONFIG', '{}')
-    reload snack.expo.io

**Comment by satya164** [comment]
Thank you for the report and debugging. We've merged a fix internally.
