### ISSUE TITLE
Typing "&&" produces "||"

### ISSUE THREAD

**Issue by chrisbolin** [expo/snack-web#8]
## Preamble

No, this is not a joke.

## Expected Behavior

When I type `&&`, `&&` shows up on the Snack editor.

## Observed Behavior

When I type `&&`, `||` shows up on the Snack editor.

### Reproduction

Because it's hard to show in a video what I type, here is a video of copying `&&` from another program and pasting it into Snack.

![nov-09-2018 09-19-09](https://user-images.githubusercontent.com/2822048/48274740-3a5be000-e401-11e8-85fc-25f19bbb39a5.gif)

## System Info

Mac OS X 10.11.6
Chrome 69.0.3497.100

## Diagnosis

Umm yeah, this is really weird. It seems to be caused by the typefaces Fira Mono and Fira Code. If I reduce the full `font-family` declaration from 

```
font-family: "Fira Code", "Fira Mono", Monaco, Menlo, "Ubuntu Mono", Consolas, source-code-pro, monospace;
```

to 

```
font-family: "Fira Mono", monospace;
/* OR */
font-family: "Fira Code", monospace;
```

I still _see this issue_.

But this works: 

```
font-family: Monaco, Menlo, "Ubuntu Mono", Consolas, source-code-pro, monospace;
```

**Comment by satya164** [comment]
This is so weird. Have you tried reinstalling Fira Mono/Fira Code on your system? Maybe you have a buggy version of the fonts? I have those fonts installed too and I can't seem to repro this.

**Comment by brentvatne** [comment]
also can't repro this

**Comment by chrisbolin** [comment]
where do Fira Mono/Fira Code come from? should they be installed with OSX?

**Comment by satya164** [comment]
@chrisbolin I don't think they are pre-installed on OS X. You might have installed them at some point.

Fira Mono: https://mozilla.github.io/Fira/
Fira Code: https://github.com/tonsky/FiraCode
